#!/bin/bash

git pull

sudo apt-get update
sudo apt-get install -y fish
sudo chsh -s /usr/bin/fish $USER

mkdir ~/.config/fish
echo "set PATH /var/tmp/coder/coder-cli $PATH" > ~/.config/fish/config.fish

cp git.fish ~/.config/fish/git.fish
fish ~/.config/fish/git.fish

cp prompt_git.fish ~/.config/fish/prompt_git.fish
fish ~/.config/fish/prompt_git.fish
