#!/bin/bash

cd ~/dotfiles

git pull

sudo apt-get update
sudo apt-get install -y fish
sudo chsh -s /usr/bin/fish $USER

mkdir ~/.config/fish
mkdir ~/.dotnet/tools
echo "set PATH /var/tmp/coder/coder-cli  ~/.dotnet/tools $PATH" > ~/.config/fish/config.fish

cp ~/dotfiles/git.fish ~/.config/fish/git.fish
fish ~/.config/fish/git.fish

cp ~/dotfiles/prompt_git.fish ~/.config/fish/prompt_git.fish
fish ~/.config/fish/prompt_git.fish
