#!/bin/bash

sudo apt-get update
sudo apt-get install -y fish
sudo chsh -s /usr/bin/fish $USER

echo "set PATH /var/tmp/coder/coder-cli $PATH" > ~/.config/fish/config.fish

mkdir fish-config

wget https://raw.githubusercontent.com/weavejester/fish-git/master/completions/git.fish > ~/.config/fish/git.fish
fish ~/.config/fish/git.fish

wget https://github.com/weavejester/fish-git/blob/master/functions/prompt_git.fish > ~/.config/fish/prompt_git.fish
fish ~/.config/fish/prompt_git.fish

